version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  core_app:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - redis

