services:
  email_service:
    smtp_host: smtp.mailtrap.io
    smtp_port: 2525
    username: your_username
    password: your_password
    from_email: no-reply@example.com

  sms_service:
    api_key: your_sms_api_key
    api_secret: your_sms_api_secret

logging:
  level: INFO
  path: /logs/app.log

security:
  roles:
    admin:
      - email_service: '*'
      - sms_service: '*'
    user:
      - email_service: send
